import "./globals.scss";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "@/_components/Header/Header";
import Footer from "@/_components/Footer/Footer";
import StoreProvider from "@/_store/StoreProvider";
import { getUser, getUserUsage } from "@/_utils/api/server/userApi";

const ubuntu = Roboto({ subsets: ["latin"], weight: ["300", "400", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [userResult, usageResult] = await Promise.all([
    getUser(),
    getUserUsage(),
  ]);

  return (
    <html lang="ru">
      <body className={ubuntu.className}>
        <StoreProvider
          initialUser={userResult.user ?? null}
          initialUsage={usageResult.usage ?? null}
        >
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
